name: Web Page Monitor

on:
  schedule:
    - cron: '0 1 * * *'  # 毎日午前10時（日本時間）に実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Cache hash file
      uses: actions/cache@v3
      with:
        path: last_hashes.json
        key: ${{ runner.os }}-hashes-${{ hashFiles('urls.txt') }}
        restore-keys: |
          ${{ runner.os }}-hashes-
    
    - name: Run monitor
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
      run: python main.py
